name: Deploy Project

on:
  push:
    branches:
      - master # Trigger deployment on push to the `main` branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Specify the Node.js version (adjust as needed)

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the project (if required)
      - name: Build Project
        run: npm run build

      # Step 5: Deploy the project in the background
      - name: Run Deployment Script in Background
        run: |
          nohup npm run start &  # This runs the server in the background

      # Step 6: Wait for the server to be ready (optional, adjust time as needed)
      - name: Wait for Server to Start
        run: sleep 10  # Adjust the time depending on how long your server needs to start

      # Step 7: Run health checks or tests after deployment (optional)
      - name: Run Health Check
        run: curl --silent --fail http://localhost:4000/health || exit 1

      # Final Step: Clean up (optional)
      - name: Clean up
        run: echo "Cleanup completed"
