name: Deploy Project

on:
  push:
    branches:
      - master # Trigger deployment on push to the `main` branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Specify the Node.js version (adjust as needed)

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the project (if required)
      - name: Build Project
        run: npm run build

      # Step 5: Deploy the project
      - name: Run Deployment Script
        run: node ./dist/server.generate.js
